[project]
name = "ayl-pos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flet>=0.83.0",
    "pyinstaller>=6.19.0",
    "tkcalendar>=1.6.1",
]

[tool.setuptools]
packages = ["src", "src.core", "src.gui", "src.legacy"]
